name: Format

on: push
jobs:

  Blacken:  # For formatting python files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/dev-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/dev-requirements.txt') }}-2
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            ${{ runner.os }}-pip-${{ hashFiles('**/dev-requirements.txt') }}
            ${{ runner.os }}-pip-key
            ${{ runner.os }}-
            ${{ runner.os }}-restore
            ${{ runner.os }}-restore-pip
      - name: Install black
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install black

      # The fun stuff
      - name: Blacken
        run: python3 -m black .
      - name: git pull
        run: |
          git config pull.ff only
          git pull --all
      - name: Commit
        run: |
          git config --global user.name 'Formatter'
          git config --global user.email 'ThatXliner@users.noreply.github.com'
          git commit -am ":robot: | :art: - :black_circle: -> Blackened files! [skip ci]" >  /dev/null || echo "Already blackened! ğŸ‘"
          git pull --all
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

  Isort:  # For sorting python module imports
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - uses: actions/cache@v2
          id: cache
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/dev-requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-pip
              ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/dev-requirements.txt') }}-2
              ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
              ${{ runner.os }}-pip-${{ hashFiles('**/dev-requirements.txt') }}
              ${{ runner.os }}-pip-key
              ${{ runner.os }}-
              ${{ runner.os }}-restore
              ${{ runner.os }}-restore-pip
        - name: Install isort
          run: |
            python3 -m pip install --upgrade pip
            python3 -m pip install isort

        # The fun stuff
        - name: Isort
          run: python3 -m isort .
        - name: git pull
          run: |
            git config pull.ff only
            git pull --all
        - name: Commit
          run: |
            git config --global user.name 'Formatter'
            git config --global user.email 'ThatXliner@users.noreply.github.com'
            git commit -am ":robot: | :art: -> Isorted files! [skip ci]" >  /dev/null || echo "Already Isorted! ğŸ‘"
            git pull --all
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            force: true
